name             'nagios'
maintainer       'Wanelo, Inc.'
maintainer_email 'dev@wanelo.com'
license          'MIT'
description      'Installs/Configures nagios'
long_description 'Installs/Configures nagios'
version          '0.1.0'

depends 'paths'
depends 'smf'
